// 🔒 DO NOT TOUCH
import { useEffect, useState } from 'react';
import { createHighlighter, type Highlighter } from 'shiki';

let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter() {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighter({
      themes: ['github-dark-dimmed'],
      langs: ['typescript', 'bash', 'diff'],
    });
  }
  return highlighterPromise;
}

export function CodePanel({ code, lang = 'typescript' }: { code: string; lang?: string }) {
  const [html, setHtml] = useState('');

  useEffect(() => {
    let cancelled = false;
    getHighlighter().then((hl) => {
      if (cancelled) return;
      const out = hl.codeToHtml(code, { lang, theme: 'github-dark-dimmed' });
      setHtml(out);
    });
    return () => {
      cancelled = true;
    };
  }, [code, lang]);

  return (
    <div className="overflow-hidden rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-black/40">
      <div className="flex gap-1.5 border-b border-white/5 px-3 py-2">
        <span className="size-2.5 rounded-full bg-red-500/70" />
        <span className="size-2.5 rounded-full bg-yellow-500/70" />
        <span className="size-2.5 rounded-full bg-green-500/70" />
      </div>
      {/* html is generated by Shiki from static, hardcoded strings — not user input */}
      <div
        className="p-4 text-sm [&_pre]:!bg-transparent"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
